# Generated by Django 5.0.6 on 2024-12-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPELEARNING", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
